eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8080

spring:
  application:
    name: api
#  security:
#    user:
#      name: cuntian
#      password: 123456
#      role: CUNTIAN
