spring:
  application:
    name: eureka

server:
  port: 8761

eureka:
  client:
    # 此应用为注册中心，false：不向注册中心注册自己。
    register-with-eureka: false
    # 注册中心职责是维护服务实例，false：不检索服务。
    fetch-registry: false